### ISSUE TITLE
TODO lists in 2018.10

### ISSUE THREAD

**Issue by SunnyMarkLiu** [SunnyMarkLiu/daily-intensive-reading-roadmap#1]
- [x] [Notes on Deep Learning for NLP](https://arxiv.org/pdf/1808.09772.pdf)
- [ ] [An Empirical Evaluation of Generic Convolutional and Recurrent Networks
for Sequence Modeling](https://arxiv.org/pdf/1803.01271.pdf)
- [x] [How Does Batch Normalization Help Optimization?](https://arxiv.org/pdf/1805.11604.pdf)

---
- [ ] REASONING ABOUT ENTAILMENT WITH NEURAL ATTENTION
- [ ] Learning Natural Language Inference with LSTM
