### ISSUE TITLE
TODO lists in the future

### ISSUE THREAD

**Issue by SunnyMarkLiu** [SunnyMarkLiu/daily-intensive-reading-roadmap#2]
---
- [ ] [The fall of RNN and LSTM](https://towardsdatascience.com/the-fall-of-rnn-lstm-2d1594c74ce0?gi=f52f89dcd41)
- [ ] Temporal convolutionan network (TCN)
- [ ] WaveNet
---
- [ ] [Pooling is neither necessary nor sufficient for appropriate deformation stability in CNNs](https://arxiv.org/abs/1804.04438)
- [ ] [DeepMind论文：CNN的变形稳定性和池化无关，滤波器平滑度才是关键](https://www.jiqizhixin.com/articles/2018-05-01)
